
// Simulated extensive dataset for Institutions
const INSTITUTIONS = [
    // Top International Universities
    { name: "Massachusetts Institute of Technology (MIT)", country: "United States", state: "Massachusetts" },
    { name: "Imperial College London", country: "United Kingdom", state: "England" },
    { name: "Stanford University", country: "United States", state: "California" },
    { name: "University of Oxford", country: "United Kingdom", state: "England" },
    { name: "Harvard University", country: "United States", state: "Massachusetts" },
    { name: "University of Cambridge", country: "United Kingdom", state: "England" },
    { name: "ETH Zurich", country: "Switzerland", state: "Zurich" },
    { name: "National University of Singapore (NUS)", country: "Singapore", state: "Singapore" },
    { name: "UCL", country: "United Kingdom", state: "England" },
    { name: "California Institute of Technology (Caltech)", country: "United States", state: "California" },
    { name: "The University of Hong Kong", country: "Hong Kong", state: "Hong Kong" },
    { name: "Nanyang Technological University, Singapore (NTU Singapore)", country: "Singapore", state: "Singapore" },
    { name: "University of Chicago", country: "United States", state: "Illinois" },
    { name: "Peking University", country: "China", state: "Beijing" },
    { name: "University of Pennsylvania", country: "United States", state: "Pennsylvania" },
    { name: "Cornell University", country: "United States", state: "New York" },
    { name: "Tsinghua University", country: "China", state: "Beijing" },
    { name: "University of California, Berkeley (UCB)", country: "United States", state: "California" },
    { name: "The University of Melbourne", country: "Australia", state: "Victoria" },
    { name: "The University of New South Wales (UNSW Sydney)", country: "Australia", state: "New South Wales" },
    { name: "Yale University", country: "United States", state: "Connecticut" },
    { name: "EPFL – École polytechnique fédérale de Lausanne", country: "Switzerland", state: "Vaud" },
    { name: "Technical University of Munich", country: "Germany", state: "Bavaria" },
    { name: "Johns Hopkins University", country: "United States", state: "Maryland" },
    { name: "Princeton University", country: "United States", state: "New Jersey" },
    { name: "The University of Sydney", country: "Australia", state: "New South Wales" },
    { name: "McGill University", country: "Canada", state: "Quebec" },
    { name: "Université PSL", country: "France", state: "Ile-de-France" },
    { name: "University of Toronto", country: "Canada", state: "Ontario" },
    { name: "Fudan University", country: "China", state: "Shanghai" },
    { name: "King's College London", country: "United Kingdom", state: "England" },
    { name: "Australian National University (ANU)", country: "Australia", state: "Australian Capital Territory" },
    { name: "The Chinese University of Hong Kong (CUHK)", country: "Hong Kong", state: "Hong Kong" },
    { name: "The University of Edinburgh", country: "United Kingdom", state: "Scotland" },
    { name: "The University of Manchester", country: "United Kingdom", state: "England" },
    { name: "Monash University", country: "Australia", state: "Victoria" },
    { name: "The University of Tokyo", country: "Japan", state: "Tokyo" },
    { name: "Columbia University", country: "United States", state: "New York" },
    { name: "Seoul National University", country: "South Korea", state: "Seoul" },
    { name: "University of British Columbia", country: "Canada", state: "British Columbia" },
    { name: "Northwestern University", country: "United States", state: "Illinois" },
    { name: "The University of Queensland", country: "Australia", state: "Queensland" },
    { name: "The Hong Kong University of Science and Technology", country: "Hong Kong", state: "Hong Kong" },
    { name: "University of Michigan-Ann Arbor", country: "United States", state: "Michigan" },
    { name: "University of California, Los Angeles (UCLA)", country: "United States", state: "California" },
    { name: "Delft University of Technology", country: "Netherlands", state: "South Holland" },
    { name: "Shanghai Jiao Tong University", country: "China", state: "Shanghai" },
    { name: "Zhejiang University", country: "China", state: "Zhejiang" },
    { name: "Yonsei University", country: "South Korea", state: "Seoul" },
    { name: "University of Bristol", country: "United Kingdom", state: "England" },
    { name: "Carnegie Mellon University", country: "United States", state: "Pennsylvania" },
    { name: "University of Amsterdam", country: "Netherlands", state: "North Holland" },
    { name: "The Hong Kong Polytechnic University", country: "Hong Kong", state: "Hong Kong" },
    { name: "New York University (NYU)", country: "United States", state: "New York" },
    { name: "The London School of Economics and Political Science (LSE)", country: "United Kingdom", state: "England" },
    { name: "Kyoto University", country: "Japan", state: "Kyoto" },
    { name: "Ludwig-Maximilians-Universität München", country: "Germany", state: "Bavaria" },
    { name: "Universiti Malaya (UM)", country: "Malaysia", state: "Kuala Lumpur" },
    { name: "KU Leuven", country: "Belgium", state: "Flemish Region" },
    { name: "Korea University", country: "South Korea", state: "Seoul" },
    { name: "Duke University", country: "United States", state: "North Carolina" },
    { name: "City University of Hong Kong (CityUHK)", country: "Hong Kong", state: "Hong Kong" },
    { name: "National Taiwan University (NTU)", country: "Taiwan", state: "Taipei" },
    { name: "The University of Auckland", country: "New Zealand", state: "Auckland" },
    { name: "University of California, San Diego (UCSD)", country: "United States", state: "California" },
    { name: "KFUPM", country: "Saudi Arabia", state: "Eastern Province" },
    { name: "University of Texas at Austin", country: "United States", state: "Texas" },
    { name: "Brown University", country: "United States", state: "Rhode Island" },
    { name: "University of Illinois Urbana-Champaign", country: "United States", state: "Illinois" },
    { name: "Université Paris-Saclay", country: "France", state: "Ile-de-France" },
    { name: "Lund University", country: "Sweden", state: "Scania" },
    { name: "Sorbonne University", country: "France", state: "Ile-de-France" },
    { name: "The University of Warwick", country: "United Kingdom", state: "England" },
    { name: "Trinity College Dublin, The University of Dublin", country: "Ireland", state: "Dublin" },
    { name: "University of Birmingham", country: "United Kingdom", state: "England" },
    { name: "The University of Western Australia", country: "Australia", state: "Western Australia" },
    { name: "KTH Royal Institute of Technology", country: "Sweden", state: "Stockholm" },
    { name: "University of Glasgow", country: "United Kingdom", state: "Scotland" },
    { name: "Universität Heidelberg", country: "Germany", state: "Baden-Württemberg" },
    { name: "University of Washington", country: "United States", state: "Washington" },
    { name: "Adelaide University", country: "Australia", state: "South Australia" },
    { name: "Pennsylvania State University", country: "United States", state: "Pennsylvania" },
    { name: "Universidad de Buenos Aires (UBA)", country: "Argentina", state: "Buenos Aires" },
    { name: "Tokyo Institute of Technology (Tokyo Tech)", country: "Japan", state: "Tokyo" },
    { name: "University of Leeds", country: "United Kingdom", state: "England" },
    { name: "University of Southampton", country: "United Kingdom", state: "England" },
    { name: "Boston University", country: "United States", state: "Massachusetts" },
    { name: "Freie Universitaet Berlin", country: "Germany", state: "Berlin" },
    { name: "Purdue University", country: "United States", state: "Indiana" },
    { name: "Osaka University", country: "Japan", state: "Osaka" },
    { name: "The University of Sheffield", country: "United Kingdom", state: "England" },
    { name: "Uppsala University", country: "Sweden", state: "Uppsala" },
    { name: "Durham University", country: "United Kingdom", state: "England" },
    { name: "University of Alberta", country: "Canada", state: "Alberta" },
    { name: "University of Technology Sydney", country: "Australia", state: "New South Wales" },
    { name: "University of Nottingham", country: "United Kingdom", state: "England" },
    { name: "KIT, Karlsruhe Institute of Technology", country: "Germany", state: "Baden-Württemberg" },
    { name: "Politecnico di Milano", country: "Italy", state: "Lombardy" },
    { name: "University of Zurich", country: "Switzerland", state: "Zurich" },

    // Indian Colleges
    { name: "Hindu College", country: "India", state: "Delhi" },
    { name: "Miranda House", country: "India", state: "Delhi" },
    { name: "Hans Raj College", country: "India", state: "Delhi" },
    { name: "Kirori Mal College", country: "India", state: "Delhi" },
    { name: "St. Stephens's College", country: "India", state: "Delhi" },
    { name: "Rama Krishna Mission Vivekananda Centenary College", country: "India", state: "West Bengal" },
    { name: "Atma Ram Santan Dharm College", country: "India", state: "Delhi" },
    { name: "St. Xavier`s College", country: "India", state: "West Bengal" },
    { name: "PSGR Krishnammal College for Women", country: "India", state: "Tamil Nadu" },
    { name: "PSG College of Arts and Science", country: "India", state: "Tamil Nadu" },
    { name: "Sri Venkateswara College", country: "India", state: "Delhi" },
    { name: "Rajagiri College of Social Sciences", country: "India", state: "Kerala" },
    { name: "Deshbandhu College", country: "India", state: "Delhi" },
    { name: "Loyola College", country: "India", state: "Tamil Nadu" },
    { name: "Presidency College", country: "India", state: "Tamil Nadu" },
    { name: "Madras Christian College", country: "India", state: "Tamil Nadu" },
    { name: "Lady Shri Ram College For Women", country: "India", state: "Delhi" },
    { name: "Shri Ram College of Commerce", country: "India", state: "Delhi" },
    { name: "Ramakrishna Mission Vidyamandira", country: "India", state: "West Bengal" },
    { name: "Thiagarajar College", country: "India", state: "Tamil Nadu" },
    { name: "Acharya Narendra Dev College", country: "India", state: "Delhi" },
    { name: "V.O. Chidambaram College", country: "India", state: "Tamil Nadu" },
    { name: "University College", country: "India", state: "Kerala" },
    { name: "Ramakrishna Mission Residential College", country: "India", state: "West Bengal" },
    { name: "St. Joseph's College", country: "India", state: "Tamil Nadu" },
    { name: "Daulat Ram College", country: "India", state: "Delhi" },
    { name: "Deen Dayal Upadhyaya College", country: "India", state: "Delhi" },
    { name: "Ramjas College", country: "India", state: "Delhi" },
    { name: "Sri Guru Tegh Bahadur Khalsa College", country: "India", state: "Delhi" },
    { name: "Delhi College of Arts & Commerce", country: "India", state: "Delhi" },
    { name: "Lady Irwin College", country: "India", state: "Delhi" },
    { name: "Sri Guru Gobind Singh College of Commerce", country: "India", state: "Delhi" },
    { name: "Gargi College", country: "India", state: "Delhi" },
    { name: "Kristu Jayanti College", country: "India", state: "Karnataka" },
    { name: "Govt Home Science College", country: "India", state: "Chandigarh" },
    { name: "Dyal Singh College", country: "India", state: "Delhi" },
    { name: "Ramanujan College", country: "India", state: "Delhi" },
    { name: "Maitreyi College", country: "India", state: "Delhi" },
    { name: "Shaheed Bhagat Singh College", country: "India", state: "Delhi" },
    { name: "Dhanalakshmi Srinivasan College of Arts & Science for Women", country: "India", state: "Tamil Nadu" },
    { name: "Stella Maris College for Women", country: "India", state: "Tamil Nadu" },
    { name: "Midnapore College", country: "India", state: "West Bengal" },
    { name: "Shyam Lal College", country: "India", state: "Delhi" },
    { name: "Sacred Heart College", country: "India", state: "Kerala" },
    { name: "Bhaskaracharya College of Applied Sciences", country: "India", state: "Delhi" },
    { name: "Bishop Heber College", country: "India", state: "Tamil Nadu" },
    { name: "Lady Brabourne College", country: "India", state: "West Bengal" },
    { name: "Pachhunga University College", country: "India", state: "Mizoram" },
    { name: "Sri Krishna Arts and Science College", country: "India", state: "Tamil Nadu" },
    { name: "Kanchi Mamunivar Govt. Institute for Postgraduate Studies and Research", country: "India", state: "Puducherry" },
    { name: "Holy Cross College, Tiruchirappalli", country: "India", state: "Tamil Nadu" },
    { name: "ST. Thomas College, Thrissur", country: "India", state: "Kerala" },
    { name: "Govt. College for Women, Thiruvananthapuram", country: "India", state: "Kerala" },
    { name: "Madras School of Social Work", country: "India", state: "Tamil Nadu" },
    { name: "St Berchmans College (Autonomous)", country: "India", state: "Kerala" },
    { name: "Fergusson College (Autonomous)", country: "India", state: "Maharashtra" },
    { name: "Kamala Nehru College", country: "India", state: "Delhi" },
    { name: "The American College", country: "India", state: "Tamil Nadu" },
    { name: "St. Teresa's College", country: "India", state: "Kerala" },
    { name: "Mar Ivanios College, Thiruvananthapuram", country: "India", state: "Kerala" },
    { name: "Queen Mary`s College", country: "India", state: "Tamil Nadu" },
    { name: "Nesamony Memorial Christian College", country: "India", state: "Tamil Nadu" },
    { name: "Ethiraj College for Women", country: "India", state: "Tamil Nadu" },
    { name: "Shaheed Rajguru College of Applied Sciences for Women", country: "India", state: "Delhi" },
    { name: "Dr. N. G. P. Arts and Science College", country: "India", state: "Tamil Nadu" },
    { name: "M S Ramaiah College of Arts, Science, and Commerce", country: "India", state: "Karnataka" },
    { name: "Government Arts College", country: "India", state: "Tamil Nadu" },
    { name: "Shivaji College", country: "India", state: "Delhi" },
    { name: "Goswami Ganesh Dutta S.D. College", country: "India", state: "Chandigarh" },
    { name: "Ayya Nadar Janaki Ammal College", country: "India", state: "Tamil Nadu" },
    { name: "St. Aloysius College", country: "India", state: "Karnataka" },
    { name: "ST. Joseph's College", country: "India", state: "Kerala" },
    { name: "Maharaja's College", country: "India", state: "Kerala" },
    { name: "Alagappa Government Arts College", country: "India", state: "Tamil Nadu" },
    { name: "Sri Ramakrishna College of Arts and Science", country: "India", state: "Tamil Nadu" },
    { name: "Vimala College", country: "India", state: "Kerala" },
    { name: "Rajah Serfoji Government College", country: "India", state: "Tamil Nadu" },
    { name: "Sacred Heart College (Autonomous)", country: "India", state: "Tamil Nadu" },
    { name: "Sri Sarada College for Women(Autonomous)", country: "India", state: "Tamil Nadu" },
    { name: "Farook College", country: "India", state: "Kerala" },
    { name: "Jamal Mohamed College", country: "India", state: "Tamil Nadu" },
    { name: "Jesus & Mary College", country: "India", state: "Delhi" },
    { name: "CMS College", country: "India", state: "Kerala" },
    { name: "Christ College (Autonomous)", country: "India", state: "Kerala" },
    { name: "A. P. C. Mahalaxmi College for Women", country: "India", state: "Tamil Nadu" },
    { name: "Ram Lal Anand College", country: "India", state: "Delhi" },
    { name: "DG Vaishnav College", country: "India", state: "Tamil Nadu" },
    { name: "Mar Athanasius College", country: "India", state: "Kerala" },
    { name: "Shri Shivaji Science College", country: "India", state: "Maharashtra" },
    { name: "Sri Ramakrishna Mission Vidyalaya College of Arts and Science", country: "India", state: "Tamil Nadu" },
    { name: "Keshav Mahavidyalya", country: "India", state: "Delhi" },
    { name: "Union Christian College", country: "India", state: "Kerala" },
    { name: "PGDAV College", country: "India", state: "Delhi" },
    { name: "St. Joseph`s College of Commerce", country: "India", state: "Karnataka" },
    { name: "Government College", country: "India", state: "Kerala" },
    { name: "Fatima College", country: "India", state: "Tamil Nadu" },
    { name: "Rajagiri School of Engineering & Technology (RSET)", country: "India", state: "Kerala" },
    { name: "Rajagiri College of Social Sciences (RCSS)", country: "India", state: "Kerala" },
    { name: "Rajagiri College of Management & Applied Sciences (RCMS)", country: "India", state: "Kerala" },
    { name: "Rajagiri Business School (RCBS)", country: "India", state: "Kerala" },
    { name: "Rajagiri Viswajyothi College of Arts & Applied Sciences", country: "India", state: "Kerala" },
    { name: "Rajagiri Hospital", country: "India", state: "Kerala" },
    { name: "Rajagiri Public School", country: "India", state: "Kerala" },
    { name: "Indian Institute of Technology (IIT) Bombay", country: "India", state: "Maharashtra" },
    { name: "Indian Institute of Technology (IIT) Delhi", country: "India", state: "Delhi" },
    { name: "Indian Institute of Technology (IIT) Madras", country: "India", state: "Tamil Nadu" },
    { name: "Indian Institute of Technology (IIT) Kanpur", country: "India", state: "Uttar Pradesh" },
    { name: "Indian Institute of Technology (IIT) Kharagpur", country: "India", state: "West Bengal" },
    { name: "Indian Institute of Management (IIM) Ahmedabad", country: "India", state: "Gujarat" },
    { name: "Indian Institute of Management (IIM) Bangalore", country: "India", state: "Karnataka" },
    { name: "Indian Institute of Management (IIM) Calcutta", country: "India", state: "West Bengal" },
    { name: "Delhi University", country: "India", state: "Delhi" },
    { name: "Jawaharlal Nehru University", country: "India", state: "Delhi" },
    { name: "Banaras Hindu University", country: "India", state: "Uttar Pradesh" },
    { name: "University of Mumbai", country: "India", state: "Maharashtra" },
    { name: "University of Mysore", country: "India", state: "Karnataka" },
    { name: "Anna University", country: "India", state: "Tamil Nadu" }
].sort((a, b) => a.name.localeCompare(b.name));

export const searchInstitutions = async (query) => {
    if (!query) return [];
    const lowerQuery = query.toLowerCase();
    await new Promise(resolve => setTimeout(resolve, 50));
    return INSTITUTIONS.filter(i => i.name.toLowerCase().includes(lowerQuery));
};
